### ISSUE TITLE
Using it locally?

### ISSUE THREAD

**Issue by hopewise** [schurig/elixir-remote-monitor#1]
Hello,

I tried to use it locally at my Mac as, but I get a prompt for:

    ssh password

so, I don't know the ssh password for locally running phoenix server.. ?

**Comment by schurig** [comment]
@hopewise try it with `erl -name debug@127.0.0.1 -setcookie your_app_name -run observer`

**Comment by hopewise** [comment]
but when I try to see the app from nodes menu, I get this error:

> =ERROR REPORT==== 2-Nov-2016::11:36:37 ===
>     node: 'app@127.0.0.1'
>     call: {observer_backend,sys_info,[]}
>     reason: {badrpc,nodedown}


but the app is already running, and serving using port 4000, I've started it like this:

    PORT=4000 MIX_ENV=dev elixir --name app --cookie your_app_name -S mix phoenix.server



what would be the problem?

**Comment by schurig** [comment]
@hopewise try `iex -S mix phoenix.server` and then run `:observer.start()` within the shell. I just tried it and this seems to work. Unfortunately, it doesn't watch your file changes.
